"""unique on email

Revision ID: 99cecf80b4ca
Revises: 8e087d640011
Create Date: 2023-09-08 21:31:42.977536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99cecf80b4ca'
down_revision = '8e087d640011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admins', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='unique')
    # ### end Alembic commands ###
